---
# Server FQDN
server_name: "{{ ansible_nodename }}"

# Nginx config
nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80"
    server_name: "{{ server_name }}"
    filename: example.com.80.conf
    extra_parameters: |
      # Reverse proxy
      location / {
          proxy_set_header    Host $host;
          proxy_set_header    X-Real-IP $remote_addr;
          proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header    X-Forwarded-Proto $scheme;

          proxy_pass          http://localhost:8080/;
          proxy_read_timeout  90;
      }
