---
- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf

- name: reload nginx
  service:
    name: nginx
    state: reloaded
