---
root_group: root
nginx_conf_path: /etc/nginx/conf.d
nginx_conf_file_path: /etc/nginx/nginx.conf
nginx_mime_file_path: /etc/nginx/mime.types
nginx_pid_file_path: /var/run/nginx.pid
nginx_vhost_path: /etc/nginx/conf.d
nginx_vhost_path_default: /etc/nginx/conf.d/default.conf
__nginx_user: nginx
