---
- name: Include OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Perform OS specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      skip: true

- name: Define nginx user
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: Ensure nginx is installed
  package:
    name: "{{ nginx_package_name }}"
    state: present

- name: Configure vhosts
  include_tasks: vhosts.yml

- name: Copy nginx configuration in place
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx service is running as configured
  service:
    name: nginx
    state: started
    enabled: true
